function [fig, txt, score] = init_events_client_window()
%INIT_EVENTS_CLIENT_WINDOW  Initialize figure for Events client
%
% Syntax:
%   [fig, txt, score] = opx.init_events_client_window();
%
% Inputs:
%   -- None --
%
% Output:
%   fig - uifigure handle
%   txt - The uitextarea that reads out state information
%   score - The uitextarea that reads out task performance/score
%
% See also: Contents

close all force;
fig = uifigure(...
    'Name', 'OPX Events', ...
    'Color', 'w', ...
    'Position', [150 250 720 600]);
g = uigridlayout(fig, [6, 1]);
txt = uitextarea(g, ...
    'FontName', 'Tahoma', ...
    'Editable', 'off', ...
    'BackgroundColor', [0.94 0.94 0.94], ...
    'Tooltip', "Center-Out Task State Readout", ...
    'FontSize', 14, ...
    'FontColor', 'k');
txt.Layout.Row = [2 6];
txt.Layout.Column = 1;
score = uitextarea(g, ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 24, ...
    'FontName', 'Tahoma', ...
    'FontWeight', 'bold', ...
    'FontColor', 'b', ...
    'Editable', 'off', ...
    'Value', {' 0 / 0 Trials (???%)'});
score.Layout.Row = 1;
score.Layout.Column = 1;
drawnow;